### ISSUE TITLE
Create CRUD hooks to manipulate the TODO items

### ISSUE THREAD

**Issue by amooz** [amooz/nextjs_todo#4]
The hooks should be able to:
- [x] Create a new TODO item
- [x] Update an existing TODO item
- [x] Remove an existing TODO item
- [x] Get a single TODO item by ID
- [x] Get all TODO items
